version: '3.3'    
services:
  bme280:
    container_name: bme280
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./secret.py:/app/secret.py
    command:
      - /app/poll-bme280.py
    restart: "no"
    depends_on:
      - influxdb
  octopus:
    container_name: octopus
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./secret.py:/app/secret.py
    command:
      - poll-octopus.py
    restart: "no"
    depends_on:
      - influxdb
  poll-internet:
    container_name: internet
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./secret.py:/app/secret.py
    command:
      - poll-internet.py
    restart: "no"
    depends_on:
      - influxdb
  patch-cloudflare:
    container_name: cloudflare
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./secret.py:/app/secret.py
    command:
      - patch-cloudflare.py
    restart: "no"
    depends_on:
      - influxdb
  flask-server:
    container_name: flask
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./secret.py:/app/secret.py
    environment:
      - FLASK_APP=./flask-server.py
    entrypoint:
      - flask
    command:
      - run
      - --host=0.0.0.0
    ports:
      - 5000:5000
    restart: "no"
    depends_on:
      - influxdb
  grafana:
    container_name: grafana
    image: grafana/grafana:9.1.5
    restart: "no"
    volumes:
      - ./volumes/etc/grafana/:/etc/grafana
      - ./volumes/var/lib/grafana:/var/lib/grafana
    depends_on:
      - influxdb
  influxdb:
    container_name: influxdb
    image: arm64v8/influxdb:1.7
    ports:
      - "8086:8086"
    volumes:
      - ./volumes/var/lib/influxdb:/var/lib/influxdb
      - ./volumes/etc/influxdb:/volumes/etc/influxdb
    restart: "no"
  swag:
    image: ghcr.io/linuxserver/swag:2.3.0
    container_name: swag
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - URL=brtkwr.com
      - SUBDOMAINS=dash,
      - ONLY_SUBDOMAINS=true,
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - PROPAGATION=20
      - EMAIL=brtknr@bath.edu
    volumes:
      - ./volumes/config:/config
    ports:
      - 443:443
      - 80:80
  wireguard:
    image: lscr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERURL=wg.brtkwr.com
      - SERVERPORT=51820
      - PEERS=2
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.0.10.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
    volumes:
      - ./volumes/etc/wireguard:/config
      - ./volumes/var/lib/wireguard:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
